# Generated by Django 5.0 on 2024-02-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_imgs')),
                ('discount_deal', models.CharField(max_length=200)),
                ('quote', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
